on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-go@v2
        with:
          go-version: "1.16.8"
      - run: make build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-go@v2
        with:
          go-version: "1.16.8"
      - run: make test
